# Site settings
title: davidcel.is
email: me@davidcel.is
description: "David Celis is a Cowboy Coder"

url: https://davidcelis.github.io
permalink: /posts/:title/

collections:
  music:
    permalink: /music/:title/
    output: true
  projects:
    permalink: /projects/:title/
    output: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM

sass:
  style: compressed

plugins:
  - jekyll-redirect-from
  - jekyll-gist

include:
  - .well-known

exclude:
  - bin
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
