title: davidcel.is
name: davidcel.is
url: http://davidcel.is
description: Wherein I write about programming and music.
highlighter: pygments
permalink: /blog/:year/:month/:day/:title

gems:
  - jekyll-mentions
  - jemoji

markdown: kramdown

include: [".well-known"]
exclude: ["vendor"]
