# Site settings
title: davidcel.is
email: me@davidcel.is
description: Wherein I write about programming and music.
url: http://davidcel.is
permalink: /blog/:year/:month/:day/:title

twitter_username: davidcelis
github_username: davidcelis

# Build settings
markdown: kramdown
highlighter: pygments

sass:
  sass_dir: css

gems:
  - jekyll-mentions
  - jemoji

include: [".well-known"]
exclude: ["vendor"]
